#!/usr/bin/env bash
set -aeuo pipefail

source .env

COMPOSE_PROJECT_NAME="${PROJECT}_${ENVIRONMENT}"
VERSION=$(cat VERSION)

echo "start modules"
echo "*************************************"
docker-compose -f ./docker-compose.yml $(find ./src-* -maxdepth 1 -name 'docker-compose.yml' -exec echo '-f {} ' \;) up -d
