docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/php:7.4-cli-alpine3.12-with-sockets
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/php:7.4-fpm-alpine3.12-with-sockets
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/nginx:1.17.6-alpine
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/redis:6.0.6-alpine3.12
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/mysql:5.7.31
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/phpmyadmin:latest
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/adminer:latest
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/elasticsearch:7.6.0-with-ik
docker pull registry.cn-hangzhou.aliyuncs.com/ulooo/elasticsearch:head-v5
